from config import(BATCH_SIZE, EPOCHS_PHASE1, EPOCHS_PHASE2, LR_PHASE1, LR_PHASE2, EARLY_STOP_PATIENCE, NUM_WORKERS, CHECKPOINT_DIR, LANE_CLASSES, N_CLASSES, VAL_SEGMENTS, TEST_SEGMENTS)
print("all config import ok")
